### ISSUE TITLE
User should be able to export all coordinate types form the output area to exported formats

### ISSUE THREAD

**Issue by dfoll** [Esri/coordinate-conversion-addin-dotnet#356]
User should be able to export a feature class of points currently in the List.  

- [ ] Whatever coordinate formats are listed in the Output box should be added as fields to the table
- [ ] When fields are added the field should be named as it is in the Output box.
- [ ] When fields for types DD, DDM, and DMS are added, three fields are added. One field containing the entire value named as above, and two parsed out fields.
- [ ] The two additional fields are named as listed above with "Lat" and "Lon" appended

     Ex.   Field 1 "DD"
     Ex.   Field 2 "DDLat"
     Ex.   Field 3 "DDLon"

- [ ] If the List was originally populated by importing the data, fields that were in the original data should be maintained and carried through to export, or until the Clear All button is used. This includes the coordinate field the original import was based upon.
- [ ] The user should be able to name the file that is exported

**Comment by dfoll** [comment]
@kgonzago more of these to come for the different output types

**Comment by NatalieCampos** [comment]
example of " Whatever coordinate formats are listed in the Output box should be added as fields to the table"

![image](https://cloud.githubusercontent.com/assets/5116835/26365849/c05c2408-3f9d-11e7-8816-51462bd24174.png)

**Comment by elinz** [comment]
@kgonzago I'm not sure if you guys have considered this, but it may be a good idea to create all field names as lowercase so you can support all different kinds of RDBMS and also check for any restricted keywords. The chances of someone setting the name of the coordinate as a keyword is extremely low, but a good practice we should implement.

**Comment by kgonzago** [comment]
@elinz Good idea!

**Comment by elinz** [comment]
@kgonzago It's been a long time since I've programmed in this area, but I thought there are interfaces/methods/etc for determining if a field name is valid or you can pass in the field name and check if it's a RDBMS restricted keyword.

**Comment by NatalieCampos** [comment]
@kgonzago Just a heads up on export from CC on the 1505 build

![image](https://cloud.githubusercontent.com/assets/5116835/26427161/737d12fc-4090-11e7-961c-f9cce9207db2.png)

**Comment by kgonzago** [comment]
@NatalieCampos This issue is currently still being worked on. Exporting attributes to CSV, KML and FC requires three different types of logic and is somewhat slow going. I'll make a determination whether it is doable to add it to this release before war room.

**Comment by topowright** [comment]
We are going to have a feature that exports to csv fc shapefile and kml with all the coords that are in the output table of the add-in.

**Comment by topowright** [comment]
@kgonzago where are we on this task? Can you give an update being that this has been in progress for a couple of days with no comments.

**Comment by BobBooth** [comment]
@kgonzago  - not sure what you were thinking about on the export logic, but might simplify things to create an in-memory feature class, then use the feature class to feature class tool, table to table tool (for CSV, or other tabular data formats), and the Layer to KML tool (yeah, you'd have to make a layer first).

**Comment by kgonzago** [comment]
@BobBooth Thanks for the suggestion. There is pre-existing logic for creating a table with fields. I'll have to simply enhance it to take into account a notation format per field situation.

**Comment by topowright** [comment]
These issues that have been broken down into smaller issues have been added as a dependency to this issue closing. @lfunkhouser I would like to make this issue a Epic, but I am not sure how to do so.

**Comment by topowright** [comment]
Adding KMZ to the format list by connecting issue: https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/495

**Comment by lfunkhouser** [comment]
Converted to Epic. Associated the 4 individual issues to this Epic.
